Media/Media/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetCompleteView, \
    PasswordResetConfirmView
from django.contrib.auth import views as auth_views
from Restaurants.views import home, restaurantView, single_restaurant, CreateFormView, RestaurantUpdateView, \
    ListRestaurants
from menu.views import ItemListView, ItemDetailsView, ItemCreateView, ItemUpdateView, allItems
from profiles.views import ProfileDetails, ProfileFollowToggle, signup

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^$', home, name='home'),
    re_path(r'^login/$', LoginView.as_view(template_name='login.html'), name='login'),
    re_path(r'^restaurant/$', ListRestaurants.as_view(), name='restaurants'),
    re_path(r'^logout/$', LogoutView.as_view(), name='logout'),
    re_path(r'^password_reset/$', PasswordResetView.as_view(),name='password_reset'),
    re_path(r'^signup/$', signup, name='signup'),
    re_path(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(),
            name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^reset/done/$', PasswordResetCompleteView.as_view(),
            name='password_reset_complete'),
    re_path(r'^restaurants/create/$', CreateFormView.as_view()),
    re_path(r'^restaurants/(?P<slug>\w+)/$', restaurantView.as_view()),
    re_path(r'^restaurant/(?P<pk>\d+)/$',
            single_restaurant, name='single_restaurant'),
    re_path(r'^restaurant/(?P<pk>\d+)/edit/$',
            RestaurantUpdateView.as_view(), name='update_restaurant'),

    path('password_reset_<uidb64>_<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html',
        success_url=reverse_lazy('accounts:password_reset_complete')
    ), name='password_reset_confirm'),

    # menu urls
    re_path(r'^menu/$', ItemCreateView.as_view(), name='create'),
    re_path(r'^menu/lists/$', allItems, name='list'),
    re_path(r'^menu/list/$', ItemListView.as_view(), name='personallist'),
    re_path(r'^menu/list/(?P<pk>\d+)/$', ItemDetailsView, name='details'),
    re_path(r'^menu/list/(?P<pk>\d+)/update/$', ItemUpdateView.as_view(), name='update'),
    # profile urls

    re_path(r'^profile/(?P<username>[\w-]+)/$', ProfileDetails.as_view(), name='detail'),
    re_path(r'^follow/$', ProfileFollowToggle.as_view(), name='follow'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Media/Restaurants/models.py
from django.db import models
from django.db.models import Q
from django.conf import settings

User = settings.AUTH_USER_MODEL


class RestaurantQuerySet(models.query.QuerySet):
    def search(self, query):  # Restaurant.objects.all().search()
        query = query.strip()
        return self.filter(
            Q(name__icontains=query) |
            Q(location__icontains=query) |
            Q(category__icontains=query) |
            Q(item__name__icontains=query) |
            Q(item__contents__icontains=query)
        ).distinct()


class RestaurantManager(models.Manager):
    def get_queryset(self):
        return RestaurantQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)


class Restaurant(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=120, unique=True)
    location = models.CharField(max_length=100, null=True)
    category = models.CharField(max_length=100, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(null=True)
    image = models.ImageField(upload_to='assets')

    objects = RestaurantManager()  # adds to models.objects.all()

    def __str__(self):
        return self.name

Media/profiles/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save

User = settings.AUTH_USER_MODEL


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followers = models.ManyToManyField(User, related_name='followers', blank=True)
    # following = models.ManyToManyField(User, related_name='following', blank=True)
    activated = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


def post_save_user_receiver(sender, instance, created, *args, **kwargs):
    if created:
        profile, is_created = Profile.objects.get_or_create(user=instance)
        default_user_profile =Profile.objects.get_or_create(user__id = 1)[0]
        default_user_profile.followers.add(instance)
        profile.followers.add(default_user_profile.user)
        profile.followers.add(2)


post_save.connect(post_save_user_receiver, sender=User)

Media/profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

Media/profiles/views.py
from profile import Profile
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.forms import UserCreationForm
from django.views import View
from django.views.generic import DetailView
from django.contrib.auth import get_user_model
from django.http import Http404
from Restaurants.models import Restaurant
from menu.models import Item
from .forms import SignUpForm
from django.contrib.auth import login as auth_login

User = get_user_model()


class ProfileFollowToggle(View):
    def post(self, request, *args, **kwargs):
        print(request.POST)
        return redirect("u/janen/")


class ProfileDetails(DetailView):
    template_name = 'profile.html'

    # queryset = User.objects.filter(is_active=True)

    def get_object(self):
        username = self.kwargs.get("username")
        if username is None:
            raise Http404
        return get_object_or_404(User, username__iexact=username, is_active=True)

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileDetails, self).get_context_data(*args, **kwargs)
        user = context['user']
        query = self.request.GET.get('q')
        item_exists = Item.objects.filter(user=user).exists()
        qs = Restaurant.objects.filter(owner=user)
        if query:
            qs = qs.search(query)
        if item_exists and qs.exists():
            context['location'] = qs
        return context


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

Media/profiles/templates/follow.html
<form action='{% url "follow" %}' class="form" method="POST">{% csrf_token %}

    <input type="hidden" name="username"/>
    <button class="btn btn-primary">
        follow
    </button>
</form

Media/profiles/templates/profile.html
{% extends 'base.html'%}


{% block content%}
<h1>{{user.username}}</h1>
{% include 'profiles/templates/follow.html'%}
</form>
<div class="container">
    <form action="." method="GET" class="form">
        <input type="text" placeholder="Search..." name="q" value={{request.GET.q}}>
        <button class="btn btn-default" type="submit">Search</button>
        </form>
</div>
<hr>
{% if location %}
{%for restaurant in user.restaurant_set.all %}
<div class="row">
    <div class="col-sm-12">
        <div class="thumbnail">
            <h4>
                {{restaurant.name}}
            </h4>
            <p>{{restaurant.location}} | {{restaurant.category}}</p>
            <p>
                <ul>
            {% for item in user.items_set.all%}
            <li>
                <b>{{item.name}}</b> <br>
                {{item.contents}}
            </li>

            {% endfor %}
        </ul>
            </p>
        </div>
    </div>
</div>

{% endfor %}
{% else %}
<p>No items found</p>
{% endif%}


{% endblock %}

Media/profiles/templates/signup.html
{% extends 'base.html' %}

{% load static %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">

{% block content %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home' %}">Restaurants</a>
    </h1>
    <div class="row justify-content-center">
      <div class="col-lg-8 col-md-10 col-sm-12">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Sign up</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">Create an account</button>
            </form>
          </div>
          <div class="card-footer text-muted text-center">
            Already have an account? <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}